### ISSUE TITLE
[Feature request] Default size settings

### ISSUE THREAD

**Issue by chiboreache** [Grubuntu/PieMenu#102]
making changes in size and radius for every pie is _a bit tedious_

**Comment by Grubuntu** [comment]
Hi

Independent customisation of each menu is an important feature of PieMenu.

Can you explain what you would like?

**Comment by dgrabulosa** [comment]
You can duplicate a pie menu and edit the tools.

**Comment by chiboreache** [comment]
> Independent customisation of each menu is an important feature of PieMenu.

i can't image that someone would ever change that size of pie's independently for every menu `~_~`


> Can you explain what you would like?

Blender is perfect example, you have one setting for all, and you can overwrite if needed

![24-11-11|02:37:56#1](https://github.com/user-attachments/assets/f4c7e87e-2365-4823-9f58-55138292af5b)

![24-11-11|02:38:20#1](https://github.com/user-attachments/assets/49d24a54-89c1-4aa2-a6ae-4a654a6e6d9a)

![24-11-11|02:39:52#1](https://github.com/user-attachments/assets/c6498298-2638-4ee3-9074-5b1319c4cac7)

**Comment by Grubuntu** [comment]
OK, I see.

Personally, I use different shapes and therefore different sizes of menus, which allows me to differentiate between the basic menus (design), the contextual menus (when a Face or Edge or Vertex is selected), the workbench access menus etc...

![PieMenus](https://github.com/user-attachments/assets/a512696c-4d7d-4115-8a2a-aa0086cf7f3b)


I don't know if it's commonly used because I've had very little feedback from users.
