### ISSUE TITLE
Using pyside6 is broken with FreeCAD 0.21

### ISSUE THREAD

**Issue by sdifru** [Grubuntu/PieMenu#76]
It seems like freecad now use qt6 and pyside6. I'm on arch linux and I got this error: `During initialization the error "No module named 'PySide2'" occurred in /home/myname/.local/share/FreeCAD/Mod/PieMenu/./InitGui.py`.

Could PieMenu use pyside6 instead of pyside2?

**Comment by Grubuntu** [comment]
It seems that we can now use pyside instead of pyside2, it  will call the pyside version which is in FreeCAD: 
https://forum.freecad.org/viewtopic.php?t=85089#p739422

Try this :  at the beginning of your InitGui.py, (/home/myname/.local/share/FreeCAD/Mod/PieMenu/./InitGui.py) edit the 3 lines:

```
    from PySide2.QtGui import QKeyEvent, QFontMetrics
    from PySide2.QtGui import QKeySequence
    from PySide2.QtCore import Qt
```

replace them by :
```

    from PySide.QtGui import QKeyEvent, QFontMetrics
    from PySide.QtGui import QKeySequence
    from PySide.QtCore import Qt
```

let me know if it works correctly I'll update for future versions.
Thanks

**Comment by sdifru** [comment]
Freecad crashed with message: `Program received signal SIGSEGV, Segmentation fault.`

**Comment by hasecilu** [comment]
I'm able to use PieMenu on Arch Linux using the latest weekly build AppImage, but `freecad` package (FC 0.21) is totally broken, also can't even compile.

**Comment by Grubuntu** [comment]
This seems to be linked to the FreeCAD 0.21 and Qt6 code. We'll have to wait for an update to FreeCAD 0.21.

https://github.com/FreeCAD/FreeCAD/issues/13303
https://github.com/FreeCAD/FreeCAD/issues/13427

Seems to work with 0.22dev

**Comment by luzpaz** [comment]
No work will be done upstream to address 0.21.x issues (only 1.0 going forward). This issue therefore should probably be closed.
