### ISSUE TITLE
Automatic pie menu selection on open editor window, referencing the actual active workbench.

### ISSUE THREAD

**Issue by dgrabulosa** [Grubuntu/PieMenu#94]
Hi.
Little improvement, I think.
Automatically select actual pie menu referencing to active workbench, when open the pie editor window.
When improve the pie menu I need to open the configuration window many times to add, remove and adjust things, and every time I open the editor I need to select the actual menu to improve it, a very repetitive task.

**Comment by Grubuntu** [comment]
Hi 

Thanks for your idea. 

I had assumed that the menu preview  was sufficient to not have to modify a menu several times, but it seems that it is not efficient enough. 

A question need to be resolved: 
should the last opened PieMenu appear when opening the settings? 
Or the possible PieMenu linked to the Workbench? 
Or the default PieMenu? 
Each user will probably have a different answer. 

As sometime there is no Workbench linked to a PieMenu I would tend to choose that the last opened PieMenu should appear and failing that, open the default PieMenu if no PieMenu has yet been opened (this happens when starting Freecad).

I will try to work on this as soon as possible.
